language: cpp
dist: trusty
git:
  depth: 3
matrix:
  include:
  - os: osx
    name: "Python 2.7 (doc build only)"
    env: PYTHON=2.7
    stage: GitHub Release
    script: skip
    deploy:
      - |
        if [ "${PYTHON:0:1}" = "3" ]; then
          if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "${PYTHON:0:1}" = "3" ]; then
            brew update; brew install python3;
          fi
          pip install --user --upgrade pip virtualenv
          virtualenv -p python$PYTHON venv
          source venv/bin/activate
        else
          brew update; brew install python2;
          pip install --user --upgrade pip virtualenv
          virtualenv -p python$PYTHON venv
          source venv/bin/activate
          pip install -r requirements.txt
          export ES_FLOW_ROOT=`pwd`
          cd $ES_FLOW_ROOT/docs/source
          python $ES_FLOW_ROOT/scripts/make_docs.py $ES_FLOW_ROOT $ES_FLOW_ROOT/docs
        fi
    provider: releases
      api_key: "$GITHUB_OAUTH_TOKEN"
      skip_cleanup: true
      on:
        tags: true
#  - os: osx
#    env: PYTHON=3.6
#  - os: windows
#    env: PYTHON=3.6
