language: cpp
dist: trusty
matrix:
  include:
  - os: osx
    env: PYTHON=2.7
  - os: osx
    env: PYTHON=3.6
  - os: windows
    env: PYTHON=3.6
before_install:
- |
  [ "${PYTHON:0:1}" = "3" ]
    if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "${PYTHON:0:1}" = "3" ]; then
      brew update; brew install python3;
    fi
    pip install --user --upgrade pip virtualenv
    virtualenv -p python$PYTHON venv
    source venv/bin/activate
  fi
install:
- |
  if [ -n "$PYTHON" ]; then
    python setup.py sdist
    pip install --verbose dist/*.tar.gz
  fi
script:
- python tests/test.py
