language: cpp
git:
  depth: 10
matrix:
  include:
  - os: osx
    name: 'JOB: Build docs and deploy to tagged release (Python 2.7)'
    env: PYTHON=2.7 HOMEBREW_NO_AUTO_UPDATE=1
    stage: GitHub Release
    install:
    - (brew install pyenv || brew upgrade pyenv) && (brew install pyenv-virtualenv || brew upgrade pyenv-virtualenv) && (brew install doxygen || brew upgrade doxygen)
    - pyenv install --skip-existing $PYTHON
    - pyenv versions
    - pyenv virtualenv $PYTHON venv && eval "$(pyenv init -)" && pyenv activate venv
    - pip install -r requirements.txt
    script:
    - export ES_FLOW_ROOT=`pwd` && echo "Set ES_FLOW_ROOT to $ES_FLOW_ROOT"
    - cd $ES_FLOW_ROOT/docs/source
    - python $ES_FLOW_ROOT/scripts/make_docs.py $ES_FLOW_ROOT $ES_FLOW_ROOT/docs
    before_deploy:
    - cd docs
    - export TRAVIS_TAG=rc-${git rev-parse --short HEAD}
    deploy:
      provider: releases
      overwrite: true
      draft: true
      api_key:
        secure: $GITHUB_ENCRYPTED_API_KEY
      file_glob: true
      file: $ES_FLOW_ROOT/docs/html/*
      on:
        repo: octue/es-flow
