language: cpp
git:
  depth: 10
matrix:
  include:
    - os: osx
      name: "JOB: Build docs and deploy to tagged release (Python 2.7)"
      env: PYTHON=2.7
      stage: GitHub Release
      install:
        - brew update
        - brew upgrade python@2 || brew install python2
        - pip install --user --upgrade pip virtualenv
        - virtualenv -p python$PYTHON venv
        - source venv/bin/activate
        - pip install -r requirements.txt
      script:
        - export ES_FLOW_ROOT=`pwd`
        - cd $ES_FLOW_ROOT/docs/source
        - python $ES_FLOW_ROOT/scripts/make_docs.py $ES_FLOW_ROOT $ES_FLOW_ROOT/docs
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        skip_cleanup: true
        on:
          tags: true
#  - os: osx
#    env: PYTHON=3.6
#  - os: windows
#    env: PYTHON=3.6
